Added Flask App
hritikksingh/Twitter-video-emotion-and-sentiment-analysis pull request #22
Opened 2022-04-18 00:58 UTC by shreya024

Related Issue : #9

2022-04-20 03:09 UTC, hritikksingh commented
@shreya024 have you done any integration testing on your local machine?

2022-05-02 02:21 UTC, hritikksingh commented
@shreya024, please respond, or else I won't be able to merge it to the main branch

2022-05-02 03:36 UTC, shreya024 commented
> @shreya024, please respond, or else I won't be able to merge it to the main branch

I am currently having my sem exams till 10th.I had checked once in my local(it was working fine).I will surely check it again in case there r any errors after 10th.

2022-05-02 18:26 UTC, anandxkumar commented
![Screenshot from 2022-05-02 23-52-16](https://user-images.githubusercontent.com/44584067/166303429-0d1dfef9-ab0d-4861-beeb-c93732ca05eb.png)

Issues:

- Formatting of HTML is wrong (as text isn't getting rendered properly).
- Choose file selects file but doesn't upload it, then is forward to browser in base directory to select the file which actually loads the video and plays it.

2022-05-02 18:30 UTC, anandxkumar requested changes
Look into the possible code causing the issues

2022-05-02 18:30 UTC, anandxkumar commented on app.py
> +def upload():
Upload isn't working properly

2022-05-31 10:29 UTC, closed without merging